import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeContextProvider from "./contexts/ThemeContext";
import TodosContextProvider from "./contexts/TodosContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Frontend Mentor Challenge Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeContextProvider>
          <TodosContextProvider>{children}</TodosContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
